fix: infer namespace from context file
gravitee-io/gravitee-kubernetes pull request #57
Opened 2023-09-26 07:59 UTC by benoitgravitee

**Issue**

https://gravitee.atlassian.net/browse/ARCHI-222

**Description**

infer namespace from context file when possible

2023-09-27 12:16 UTC, remibaptistegio requested changes
Just one comment to fix I guess, otherwise lgtm 😉

2023-09-28 07:26 UTC, benoitgravitee commented on gravitee-kubernetes-client/src/main/java/io/gravitee/kubernetes/client/config/KubernetesConfig.java
> +     *     <li><code>null</code> if no context can be loaded from config file, or an error occurs reading cluster information</li>
<li>Loaded from the cluster information in which gravitee is deployed</li>

2023-09-29 14:00 UTC, guillaumelamirand approved these changes

2023-09-29 14:46 UTC, merged

2023-09-29 14:49 UTC, graviteeio commented
:tada: This PR is included in version 2.1.1 :tada:

The release is available on:
- `2.1.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-kubernetes/releases/tag/2.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: